import mongoose from "mongoose";

const userSchema = mongoose.Schema({
  title: { type: String, required: false },
  price: { type: String, required: false },
  endSelectDate: { type: String, required: false },
  nights: { type: String, required: false },
  Status: { type: String, required: false },
  trendingHeading: { type: String, required: false },
  subTitle: { type: String, required: false },
  days: { type: String, required: false },
  location: { type: String, required: false },
  pickUp: { type: String, required: false },
  dropOff: { type: String, required: false },
  bannerImage: { type: String, default: null },
  cardImage: { type: String, default: null },
  categories: [{ type: String }],
  overview: { type: String, required: false },
  itenarryImg: { type: String, default: null },
  type: { type: String, required: false },
  numberOfDays: { type: String, default: false },
  numberOfSeats: { type: String, default: false },
  selectDate: { type: String, default: false },
  date: { type: Date, required: false },
  firstBookingPrice: { type: String, required: false },
  Inclusion: { type: String, default: "" },
  Exclusion: { type: String, default: "" },
  ThingsToCarry: { type: String, default: "" },
  Cancellation: { type: String, default: "" },
  discount: [{ type: String }],
  gallaryImages: [{ type: String }],
  reviews: [{ type: String }],
  ratings: [{ type: String }],
  vendors: [{ type: String }],
  enableBooking: { type: Boolean, default: false },
  Trending: { type: Boolean, default: false },
  enableEnquire: { type: Boolean, default: false },
  addsection: { type: String, default: false },
  addDays: { type: String, default: false },
  strikePrice: { type: String, required: false },
  commissionRate: { type: String, required: false },
  tripOff: { type: Number, default: 0 },
  metaDescription: { type: String, required: false, default: "" },
  seoSlug: { type: String, required: false, default: "" },
  seoTitle: { type: String, required: false, default: "" },
  host: { type: mongoose.Schema.Types.ObjectId, ref: 'Host', required: false },
  // addsection: [{ type: String }],
});

export const Trips = mongoose.model("Trips", userSchema);
